기본 세팅

In [ ]:
# scikit-learn에 내장된 예제 데이터셋을 불러옵니다.
from sklearn import datasets
# iris 데이터셋을 변수에 저장합니다.
df = datasets.load_iris()

In [ ]:
# 데이터가 제대로 불러와졌는지 앞부분을 확인합니다.
df # 출력해서 확인

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

classfication >

In [ ]:
# 예측해야 할 정답(label 또는 target) 컬럼을 y에 저장합니다.
y = df.target

# 모델 입력에 사용할 특징(feature) 데이터를 X에 저장합니다.
X = df.data


# 데이터를 학습용과 테스트용으로 나누기 위한 함수를 불러옵니다.
from sklearn.model_selection import train_test_split

# 전체 데이터 중 75%는 학습, 25%는 테스트에 사용합니다.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

In [ ]:
# 로지스틱 회귀는 분류 문제에서 기준 모델로 자주 사용됩니다.
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# 로지스틱 회귀 모델 객체를 생성합니다.
model = LogisticRegression(max_iter=5000)

# 학습 데이터로 모델을 훈련합니다.
model.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred = model.predict(X_test)

print("Logistic Regression 정확도")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print(accuracy_score(y_test, pred))
print("Confusion Matrix")
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print(confusion_matrix(y_test, pred))

Logistic Regression 정확도
0.9736842105263158
Confusion Matrix
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
# 결정 트리는 조건을 나누며 분류 규칙을 학습하는 모델입니다.
from sklearn.tree import DecisionTreeClassifier

# 결정 트리 분류 모델을 생성합니다. random_state는 결과 재현을 위한 값입니다.
clf_dt = DecisionTreeClassifier(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
clf_dt.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print (accuracy_score(y_test, pred_dt))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
# 랜덤 포레스트는 여러 결정 트리를 묶어 분류 성능을 높이는 앙상블 모델입니다.
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# pandas는 표 형태 데이터 처리, numpy는 수치 계산에 사용합니다.
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
# 랜덤 포레스트 분류 모델을 생성합니다.
rf_clf = RandomForestClassifier(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
rf_clf.fit(X_train, y_train)
# 테스트 데이터에 대한 예측값을 생성합니다.
pred = rf_clf.predict(X_test)
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print(accuracy_score(y_test,pred))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
# knn

# KNN은 가까운 이웃 데이터의 라벨을 보고 분류하는 모델입니다.
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# 가장 가까운 이웃 3개를 기준으로 분류하도록 설정합니다.
knn = KNeighborsClassifier(n_neighbors=3)

# 학습 데이터로 모델을 훈련합니다.
knn.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_knn = knn.predict(X_test)

print("\n--- KNN Classifier ---")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print("Accuracy:", accuracy_score(y_test, pred_knn))
print("Confusion Matrix:")
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print(confusion_matrix(y_test, pred_knn))


--- KNN Classifier ---
Accuracy: 0.9736842105263158
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


regression >

In [ ]:
# 예측해야 할 정답(label 또는 target) 컬럼을 y에 저장합니다.
y = df.target

# 모델 입력에 사용할 특징(feature) 데이터를 X에 저장합니다.
X = df.data



# 데이터를 학습용과 테스트용으로 나누기 위한 함수를 불러옵니다.
from sklearn.model_selection import train_test_split

# 전체 데이터 중 75%는 학습, 25%는 테스트에 사용합니다.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

In [ ]:
# 선형 회귀는 연속적인 숫자 값을 예측하는 기본 회귀 모델입니다.
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# 선형 회귀 모델 객체를 생성합니다.
model = LinearRegression()

# 학습 데이터로 모델을 훈련합니다.
model.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred = model.predict(X_test)

# MSE는 실제값과 예측값의 차이를 제곱해 평균낸 회귀 오차입니다.
print("MSE:", mean_squared_error(y_test, pred))

MSE: 0.06325336904344211


In [ ]:
# 결정 트리 회귀는 데이터를 조건별로 나누어 연속값을 예측합니다.
from sklearn.tree import DecisionTreeRegressor

# 결정 트리 회귀 모델을 생성합니다.
dt = DecisionTreeRegressor(random_state=0)

# 학습 데이터로 모델을 훈련합니다.
dt.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_dt = dt.predict(X_test)

print("\n--- Decision Tree Regressor ---")
# MSE는 실제값과 예측값의 차이를 제곱해 평균낸 회귀 오차입니다.
print("MSE:", mean_squared_error(y_test, pred_dt))


--- Decision Tree Regressor ---
MSE: 0.02631578947368421


In [ ]:
# 랜덤 포레스트 회귀는 여러 트리의 예측을 평균내어 안정적인 예측을 만듭니다.
from sklearn.ensemble import RandomForestRegressor

# 랜덤 포레스트 회귀 모델을 생성합니다.
rf = RandomForestRegressor(random_state=0)

# 학습 데이터로 모델을 훈련합니다.
rf.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_rf = rf.predict(X_test)

print("\n--- Random Forest Regressor ---")
# MSE는 실제값과 예측값의 차이를 제곱해 평균낸 회귀 오차입니다.
print("MSE:", mean_squared_error(y_test, pred_rf))


--- Random Forest Regressor ---
MSE: 0.025013157894736838


In [ ]:
# knn

# KNN 회귀는 가까운 이웃들의 값을 참고해 연속값을 예측합니다.
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

# 가장 가까운 이웃 3개의 평균적인 정보를 이용하도록 설정합니다.
knn = KNeighborsRegressor(n_neighbors=3)

# 학습 데이터로 모델을 훈련합니다.
knn.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_knn = knn.predict(X_test)

print("\n--- KNN Regressor ---")
# MSE는 실제값과 예측값의 차이를 제곱해 평균낸 회귀 오차입니다.
print("MSE:", mean_squared_error(y_test, pred))


--- KNN Regressor ---
MSE: 0.06325336904344211
