In [4]:


# pandas는 표 형태 데이터 처리, numpy는 수치 계산에 사용합니다.
import pandas as pd
import numpy as np


# 사용할 CSV 파일의 경로를 지정합니다.
path = '/content/drive/MyDrive/notebook/diabetes.csv'

# DataFrame으로 읽기
# CSV 파일을 읽어 pandas DataFrame으로 만듭니다.
df = pd.read_csv(path)

# 데이터가 제대로 불러와졌는지 앞부분을 확인합니다.
df

# 예측해야 할 정답(label 또는 target) 컬럼을 y에 저장합니다.
y=df['Outcome']
y.value_counts()
y

# 모델 입력에 사용할 특징(feature) 데이터를 X에 저장합니다.
X=df.drop('Outcome',axis=1)
X.head()

# 데이터를 학습용과 테스트용으로 나누기 위한 함수를 불러옵니다.
from sklearn.model_selection import train_test_split

# 전체 데이터 중 75%는 학습, 25%는 테스트에 사용합니다.
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)



# 로지스틱 회귀는 분류 문제에서 기준 모델로 자주 사용됩니다.
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# 결정 트리는 조건을 나누며 분류 규칙을 학습하는 모델입니다.
from sklearn.tree import DecisionTreeClassifier

# 로지스틱 회귀 모델 객체를 생성합니다.
clf_lr = LogisticRegression(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
clf_lr.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print (accuracy_score(y_test, pred_lr))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred_lr))



--- Logistic Regression Classifier ---
0.796875
[[116  14]
 [ 25  37]]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
# 결정 트리 분류 모델을 생성합니다. random_state는 결과 재현을 위한 값입니다.
clf_dt = DecisionTreeClassifier(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
clf_dt.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print (accuracy_score(y_test, pred_dt))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.71875
[[102  28]
 [ 26  36]]


In [6]:
# 랜덤 포레스트는 여러 결정 트리를 묶어 분류 성능을 높이는 앙상블 모델입니다.
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# pandas는 표 형태 데이터 처리, numpy는 수치 계산에 사용합니다.
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
# 랜덤 포레스트 분류 모델을 생성합니다.
rf_clf = RandomForestClassifier(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
rf_clf.fit(X_train, y_train)
# 테스트 데이터에 대한 예측값을 생성합니다.
pred = rf_clf.predict(X_test)
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print(accuracy_score(y_test,pred))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.7708333333333334
[[116  14]
 [ 30  32]]
