In [1]:
# worst compactness

# pandas는 표 형태 데이터 처리, numpy는 수치 계산에 사용합니다.
import pandas as pd
import numpy as np

# 데이터 불러오기
# 사용할 CSV 파일의 경로를 지정합니다.
path = '/content/drive/MyDrive/notebook/breast_cancer.csv'
# CSV 파일을 읽어 pandas DataFrame으로 만듭니다.
df = pd.read_csv(path)

# 분석에 필요 없는 인덱스 컬럼을 제거합니다.
df = df.drop('Unnamed: 0', axis=1)

# 예측해야 할 정답(label 또는 target) 컬럼을 y에 저장합니다.
y = df['label']


# 모델 입력에 사용할 특징(feature) 데이터를 X에 저장합니다.
X = df.drop('label', axis=1)


# 데이터를 학습용과 테스트용으로 나누기 위한 함수를 불러옵니다.
from sklearn.model_selection import train_test_split

# 전체 데이터 중 75%는 학습, 25%는 테스트에 사용합니다.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)



In [2]:
# 로지스틱 회귀는 분류 문제에서 기준 모델로 자주 사용됩니다.
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# 로지스틱 회귀 모델 객체를 생성합니다.
model = LogisticRegression(max_iter=5000)

# 학습 데이터로 모델을 훈련합니다.
model.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred = model.predict(X_test)

print("Logistic Regression 정확도")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print(accuracy_score(y_test, pred))
print("Confusion Matrix")
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print(confusion_matrix(y_test, pred))

Logistic Regression 정확도
0.951048951048951
Confusion Matrix
[[52  1]
 [ 6 84]]


In [4]:

# 결정 트리는 조건을 나누며 분류 규칙을 학습하는 모델입니다.
from sklearn.tree import DecisionTreeClassifier

# 결정 트리 분류 모델을 생성합니다. random_state는 결과 재현을 위한 값입니다.
clf_dt = DecisionTreeClassifier(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
clf_dt.fit(X_train, y_train)

# 테스트 데이터에 대한 예측값을 생성합니다.
pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print (accuracy_score(y_test, pred_dt))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.8811188811188811
[[50  3]
 [14 76]]


In [5]:
# 랜덤 포레스트는 여러 결정 트리를 묶어 분류 성능을 높이는 앙상블 모델입니다.
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# pandas는 표 형태 데이터 처리, numpy는 수치 계산에 사용합니다.
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
# 랜덤 포레스트 분류 모델을 생성합니다.
rf_clf = RandomForestClassifier(random_state=0)
# 학습 데이터로 모델을 훈련합니다.
rf_clf.fit(X_train, y_train)
# 테스트 데이터에 대한 예측값을 생성합니다.
pred = rf_clf.predict(X_test)
# 정확도는 전체 테스트 데이터 중 맞힌 비율을 의미합니다.
print(accuracy_score(y_test,pred))
# 혼동 행렬은 실제 클래스와 예측 클래스의 대응 관계를 보여줍니다.
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.972027972027972
[[52  1]
 [ 3 87]]
