In [1]:
# worst compactness

import pandas as pd
import numpy as np

# 데이터 불러오기
path = '/content/drive/MyDrive/notebook/breast_cancer.csv'
df = pd.read_csv(path)

df = df.drop('Unnamed: 0', axis=1)

y = df['label']


X = df.drop('label', axis=1)


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)



In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

model = LogisticRegression(max_iter=5000)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Logistic Regression 정확도")
print(accuracy_score(y_test, pred))
print("Confusion Matrix")
print(confusion_matrix(y_test, pred))

Logistic Regression 정확도
0.951048951048951
Confusion Matrix
[[52  1]
 [ 6 84]]


In [4]:

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.8811188811188811
[[50  3]
 [14 76]]


In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.972027972027972
[[52  1]
 [ 3 87]]
