In [1]:

import pandas as pd
import numpy as np

# 데이터 불러오기
path = '/content/drive/MyDrive/Colab Notebooks/wine.csv'
df = pd.read_csv(path)

# df = df.drop('Unnamed: 0', axis=1)

df.head()

y = df['Wine']

X = df.drop('Wine', axis=1)


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

model = LogisticRegression(max_iter=5000)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Logistic Regression 정확도")
print(accuracy_score(y_test, pred))
print("Confusion Matrix")
print(confusion_matrix(y_test, pred))

Logistic Regression 정확도
0.9777777777777777
Confusion Matrix
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]


In [3]:

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]


In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

pred_knn = knn.predict(X_test)

print("\n--- KNN Classifier ---")
print("Accuracy:", accuracy_score(y_test, pred_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_knn))


--- KNN Classifier ---
Accuracy: 0.7333333333333333
Confusion Matrix:
[[14  1  1]
 [ 1 18  2]
 [ 4  3  1]]
